### ISSUE TITLE
Issue with xclickroot in spectrwm

### ISSUE THREAD

**Issue by davisrichard437** [phillbush/xclickroot#4]
Hello!

I'm having some trouble getting xclickroot to work. Here is some background information:

- OS: Arch Linux
- DE: spectrwm
- Package source: aur/xmenu (script located at ~/.local/bin/menu) and aur/xclickroot-git

I start xclickroot-git in ~/.xprofile:

    xclickroot -r ~/.local/bin/menu

This setup works in three other of my window managers (awesome, qtile, and xmonad), but not in spectrwm.

In accordance with your advice on Issue #3, I tried to find out if another device was grabbing the mouse, but there was none. As such, after killing xclickroot, I was able to start it again in the terminal, but nothing happened when right-clicking the root window. Would you happen to know why this is, or how I might fix this?

**Comment by phillbush** [comment]
Hello.

Does xclickroot(1) display any error when you start it again?

**Comment by phillbush** [comment]
I'm reading spectrwm's code and it seems that it grabs the mouse buttons to bind a mouse click on the root window to a command. If the mouse buttons are already grabbed, xclickroot cannot re-grab them.  
If spectrwm already implement what xclickroot does, I recommend you to use spectrwm's binding feature rather than using xclickroot.

If I understood correctly, you need to add this to your spectrwm.conf:

```none
program[xmenu]  = xmenu.sh
bind[xmenu]     = Button3
```

**Comment by davisrichard437** [comment]
That works perfectly, thank you very much!
